# Spring Application Name
spring.application.name=PourControl

# Database Configuration (Development DB)
spring.datasource.url=jdbc:mysql://pourcontroldb.kianserver.uk:3306/pourControlDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=pourcontrol
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Spoonacular External API
spoonacular.api.key=4d63d7063cd645ac8450faf5c5d85c5a
spoonacular.api.url=https://api.spoonacular.com/recipes